### PR TITLE
Update supported diagram types

### PR DESCRIPTION
**Pull request by felixvanoost**
Adds the following new diagram types as supported in Kroki [0.23.0](https://github.com/yuzutech/kroki/releases/tag/v0.23.0):

- symbolator
- d2
- tikz
- wireviz
- dbml

I've also added a basic development container with Node.js and the VS code extension dependencies to facilitate development and testing. 

### Symbolator
Symbolator

### D2
D2

### TiKZ
TiKZ

### WireViz
WireViz

### DBML
DBML

### CODE REVIEW

**Comment by felixvanoost** [comment]
@TECH7Fox Let me know if there's anything I can do to move this along!

**Comment by felixvanoost** [comment]
@TECH7Fox Would you be interested in merging this?

**Comment by TECH7Fox** [comment]
Ah sorry didn't see this message. Did you test it already?

**Comment by felixvanoost** [comment]
@TECH7Fox No worries! I've added screenshots for each new diagram type to the MR description as well as a VS Code `.devcontainer` configuration with a minimal build environment.

**Comment by TECH7Fox** [comment]
Looks good, thank you for the PR!

**Pull request merged**
